Fixed syntax for Session.ixx module
Now all should work fine when I try to crate a Session object, but I get error C1001 in linking phase. This is very strange, since I tested in another project that simple modules and module partitions work fine.